In [1]:
#Numpy 객체
import numpy as np

In [2]:
#배열 생성
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [5]:
np.array([[1,2],
          [3,4]])

array([[1, 2],
       [3, 4]])

In [6]:
np.array([1,2,3,4]).reshape([2,2])

array([[1, 2],
       [3, 4]])

In [9]:
#색인
array = np.array([[1,2,3], [4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
array[0]

array([1, 2, 3])

In [11]:
array[1]

array([4, 5, 6])

In [12]:
array[1][1]

5

In [13]:
array[1,1] # row index, col index

5

In [14]:
#매서드, 어트리뷰트
array.ndim   #몇 차원이냐?,  n = number of 라는 뜻

2

In [15]:
array.shape  #각 차원의 길이

(2, 3)

In [16]:
array.sum()  #합

21

In [17]:
array.std()  #표준편차

1.707825127659933

In [18]:
#다양한 함수
nums = np.array([1, 2, 2, 3])
nums

array([1, 2, 2, 3])

In [19]:
set(nums) #집함 (중복 제외)

{1, 2, 3}

In [20]:
len(nums) #길이

4

In [21]:
np.unique(nums) # 어레이, 중복 제거

array([1, 2, 3])

In [22]:
np.arange(start = 5, stop = 20, step = 5)

array([ 5, 10, 15])

In [23]:
np.where(nums == 2, "ok!", "no!")

array(['no!', 'ok!', 'ok!', 'no!'], dtype='<U3')

In [25]:
#Pandas 객체
import pandas as pd

In [27]:
ser = pd.Series([1, 2, 3])
ser

0    1
1    2
2    3
dtype: int64

In [28]:
ser.values

array([1, 2, 3], dtype=int64)

In [29]:
ser.index

RangeIndex(start=0, stop=3, step=1)

In [30]:
#시리즈의 생성 및 메서드
pd.Series([1,2,3,3,4])

0    1
1    2
2    3
3    3
4    4
dtype: int64

In [31]:
pd.Series([1,2,3], index = ["a", "b", "c"])

a    1
b    2
c    3
dtype: int64

In [32]:
ser.sum()  # 합계

6

In [33]:
ser.min()  # 최소값

1

In [34]:
ser.max()  # 최대값

3

In [35]:
ser.mean()  # 평균

2.0

In [36]:
ser.std()  # 표준편차

1.0

In [37]:
ser.skew()  # 왜도

0.0

In [38]:
ser.kurt()  # 첨도

nan

In [39]:
ser.unique()  # 고유값

array([1, 2, 3], dtype=int64)

In [41]:
ser.idxmax()  # 최대값의 위치

2

In [43]:
ser.idxmin()  # 최소값의 위치

0

In [42]:
ser.isin([1,2])  # 포함 여부 검사

0     True
1     True
2    False
dtype: bool

In [44]:
ser.isin([1,2]).sum()  # 1, 2가 몇개 있느냐?

2

In [47]:
True + True + False # True = 1, False = 0

2

In [48]:
#색인
ser[0]

1

In [50]:
ser[[1,2]]

1    2
2    3
dtype: int64

In [51]:
ser[1:]

1    2
2    3
dtype: int64

In [52]:
ser[:2]

0    1
1    2
dtype: int64

In [53]:
ser[:-1]

0    1
1    2
dtype: int64

In [54]:
#데이터프레임 개요
pd.DataFrame([1,2,2],[3,3,4])

0
3  1
3  2
4  2

In [55]:
pd.DataFrame({"aa":[1,2,3],"bb":[2,3,4]})

aa  bb
0   1   2
1   2   3
2   3   4

In [58]:
pd.DataFrame([[1,2],[3,4],[5,6]], columns=["xx","yy"])

xx  yy
0   1   2
1   3   4
2   5   6

In [60]:
pd.DataFrame(np.arange(4).reshape((2,2)), columns = ["a", "b"])

a  b
0  0  1
1  2  3

In [69]:
df = pd.DataFrame({"aa":[1,2,3],
                   "bb":[2,3,4]})
df

aa  bb
0   1   2
1   2   3
2   3   4

In [70]:
df.aa

0    1
1    2
2    3
Name: aa, dtype: int64

In [62]:
df["aa"]

0    1
1    2
2    3
Name: aa, dtype: int64

In [63]:
df["aa"][:2]

0    1
1    2
Name: aa, dtype: int64

In [64]:
df.iloc[:,0]  # 정수 기반 인덱싱

0    1
1    2
2    3
Name: aa, dtype: int64

In [65]:
df.loc[:, "aa"] # 문자 기반 인덱싱

0    1
1    2
2    3
Name: aa, dtype: int64

In [66]:
df.iloc[:2, :]

aa  bb
0   1   2
1   2   3

In [67]:
df.iloc[:, 0]

0    1
1    2
2    3
Name: aa, dtype: int64

In [68]:
df.loc[:, "aa"]

0    1
1    2
2    3
Name: aa, dtype: int64

In [ ]:
# 데이터 요약
"""
crosstab (빈도표)
두 변수를 조합하여 살펴볼 때 사용하는 Pandas 함수
normalize 인자에 True, 1, 0 값을 할당하여 값을 정규화 할 수 있음
"""

In [71]:
pd.crosstab(df["aa"], df["bb"])

bb  2  3  4
aa         
1   1  0  0
2   0  1  0
3   0  0  1

In [ ]:
"""
groupby
특정 변수를 기준으로 요약 연산을 할 때 활용하는 데이터프레임의 메서드
두 개 이상의 변수를 기준으로 연산할 경우 변수명을 리스트로 묶음
"""

In [72]:
df.groupby("aa")["bb"].sum()

aa
1    2
2    3
3    4
Name: bb, dtype: int64